### ISSUE TITLE
OSM

### ISSUE THREAD

**Issue by sheldonelectric** [openchargemap/ocm-app#2]
Please add the charging stations on osm.org
Retrieve dots from available in osm.org into openchargemap

**Comment by webprofusion-chrisc** [comment]
Hi, we have previously proposed a data import into OSM but this was rejected because of the variety of Open Data licenses involved. 

The general consensus (several years ago) was that OSM prefer crowdsourced data that originates from their own platform. A percentage of our data is also imported, which involves a variety of other licenses, as far as I know this makes it impossible to relicense as ODbL for OSM. 

Really, the restrictions are on their side and they can otherwise have the data whenever they like.
