### ISSUE TITLE
Photo submission for pending location

### ISSUE THREAD

**Issue by zeroping** [openchargemap/ocm-app#3]
I submitted a new location, and then went to add a photo to help whoever approves it.

Once the photo upload finished, I got the error message "The location you are attempting to view does not exist or has been removed", and the photo does not appear to have been uploaded.

Version 5.2.1 from Google Play on Android 8.0.0

It seems like photo submission is pretty important for a new site. Let me know if I need to provide more debug info.

**Comment by webprofusion-chrisc** [comment]
Hi, I think the issue here is that it the location has been added but not yet approved by an editor. I'm guessing its this one: https://openchargemap.org/site/poi/details/105868 - the current android app is intended to be replaced by the https://map.openchargemap.io app eventually, I just ran out of steam developing it - the last mile is always the hardest!

**Comment by zeroping** [comment]
Yep, that's the one. What's really interesting is that my photo does show up now. So maybe I managed to add a photo, but failed to view it?

And yes - I had no trouble uploading other photos for already-approved locations. I figure that photos would be really helpful for editors when proofing new locations. 

It might not be worth fixing if there's a new app in the works; just letting you know it was a desired workflow.
